---
- name: install | Installing Pre-Reqs
  yum:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - createrepo
    - cronie
    - httpd
    - rsync

- name: install | Ensuring Apache Is Started and Starts On Boot
  service:
    name: httpd
    state: started
    enabled: true
  become: true
